image_cols: 640
image_rows: 480
bad_point: 9.9
cv_fs_image_id: "avg_image"
num_images_for_background: 3
person_distance: 1.5
min_distance_near_camera: 0.75
camera_info_topic: /camera_body/depth_registered/camera_info
rows_rollator_offset: 120
depth_image_sub_topic: /camera_body/depth_registered/image_raw
rgb_image_topic: /camera_body/rgb/image_raw
avg_image_path: background_image/avg_image.yml