lower_limit: 0.0
upper_limit: 1.0

depth_image_topic: /camera/depth_registered/image_raw
rgb_image_topic: /camera/rgb/image_raw
depth_image_pub: /biotracking/raw_image
background_threshold: 70
person_distance: 1.5
bottom_factor: 1.
shouldOutput: false
frame_id: camera_depth_frame
usePCL: false
person_hips: -0.1
person_neck: 0.4
useCentroid: true
camera_info_topic: /camera/depth_registered/info
