lower_limit: 0.0
upper_limit: 1.0

#depth_image_topic: /camera/depth_registered/image_raw
depth_image_topic: /camera_body/depth_registered/image_raw
#rgb_image_topic: /camera/rgb/image_raw
rgb_image_topic: /camera_body/rgb/image_raw
depth_image_pub: /biotracking/raw_image
num_images_for_background: 3
person_distance: 1.5
bottom_factor: 1.
shouldOutput: false
camera_frame_id: camera_depth_frame
usePCL: false
#person_hips: -0.1
#person_neck: 0.4
person_hips: 0.2
hips_height_world: 0.73
camera_height_world: 0.9
person_hips_frame_id: base_link
person_neck: 0.4
useCentroid: true
#camera_info_topic: /camera/depth/camera_info
camera_info_topic: /camera_body/depth_registered/camera_info
#camera_angle_radians: 0.26
camera_angle_radians: 0.02
shoulder_window_size: 10
avg_image_path: background_image/avg_image.yml
min_distance_near_camera: 0.75
out: 1
rows_rollator_offset: 140